### ISSUE TITLE
panic: Base level can't be zero.

### ISSUE THREAD

**Issue by atlas-comstock** [kelindar/talaria#99]
```
panic: Base level can't be zero.

goroutine 935 [running]:
github.com/dgraph-io/badger/v3.(*levelsController).fillTablesL0ToLbase(0x400091e4d0, 0x4000837770, 0x4000837400)
        /go/src/talaria/vendor/github.com/dgraph-io/badger/v3/levels.go:1168 +0x610
github.com/dgraph-io/badger/v3.(*levelsController).fillTablesL0(0x400091e4d0, 0x4000837770, 0x1d3c40c)
        /go/src/talaria/vendor/github.com/dgraph-io/badger/v3/levels.go:1229 +0x30
github.com/dgraph-io/badger/v3.(*levelsController).doCompact(0x400091e4d0, 0x2, 0x0, 0x3ff3333333333333, 0x3ff028509ce1b939, 0x0, 0x0, 0x0, 0x0, 0x40004c80a8, ...)
        /go/src/talaria/vendor/github.com/dgraph-io/badger/v3/levels.go:1505 +0x1b0
github.com/dgraph-io/badger/v3.(*levelsController).runCompactor.func2(0x0, 0x3ff3333333333333, 0x3ff028509ce1b939, 0x0, 0x0, 0x0, 0x0, 0x40004c8048, 0x3, 0x3, ...)
        /go/src/talaria/vendor/github.com/dgraph-io/badger/v3/levels.go:465 +0x58
github.com/dgraph-io/badger/v3.(*levelsController).runCompactor.func3(0x40007e3f30)
        /go/src/talaria/vendor/github.com/dgraph-io/badger/v3/levels.go:488 +0xf8
github.com/dgraph-io/badger/v3.(*levelsController).runCompactor(0x400091e4d0, 0x2, 0x40007c65a0)
        /go/src/talaria/vendor/github.com/dgraph-io/badger/v3/levels.go:517 +0x28c
created by github.com/dgraph-io/badger/v3.(*levelsController).startCompact
        /go/src/talaria/vendor/github.com/dgraph-io/badger/v3/levels.go:354 +0x7c
```

**Comment by atlas-comstock** [comment]
May be related to https://discuss.dgraph.io/t/panic-base-level-cant-be-zero/15715/8

**Comment by kelindar** [comment]
Looks like misconfiguration?

**Comment by atlas-comstock** [comment]
@kelindar seems the default setting of base level for ingestion is too little.
